### ISSUE TITLE
Data model harmonization.

### ISSUE THREAD

**Issue by dstruck** [kunai-project/kunai#17]
Hello,

For **execve** events, the *data.exe* field is an object. For events like **read_config** and  **file_unlink**, the *data.exe* field is a string.

To ease data ingestion it could make sense to use the same data type for a specific field name.

**Comment by qjerome** [comment]
Hi @dstruck,

I understand your concern, this was originally thought like that not to duplicate hashes information on all the event and save space and a little of processing as well. I will keep this in mind and fix it for the next stable release.

**Comment by dstruck** [comment]
Not all fields have to be filled out. So for events where it makes sense, hash information can be left out. One should just consistently use the same name hierarchy to store the same type of information, e.g. *data.exe.file* for the filename. Makes also analyzing afterwards easier ;-)
