### ISSUE TITLE
aarch64 compability

### ISSUE THREAD

**Issue by ReturnRei** [kunai-project/kunai#71]
Some features aren't working on aarch64

Linux version
`Linux debian 6.1.0-22-arm64 #1 SMP Debian 6.1.94-1 (2024-06-21) aarch64 GNU/Linux`

Some stats on the error log file (running for a few hours)
`cat error.log  | cut -d " " -f 4 | sort | uniq -c`
```
    280 probes::clone
    159 probes::connect
    192 probes::execve
16407863 probes::fs
   3613 probes::send_data
... [other errors]
```

**Comment by qjerome** [comment]
One instance of the bugs causing all these messages is very strange.
It seems arguments I get of the kprobes are null, while they should not.
I've ask the questions on the Aya Discord channel, let's see what comes up: https://discord.com/channels/855676609003651072/855676609003651075/1264223065429119007

**Comment by qjerome** [comment]
Got a fix for this ! It was simpler than expected ... It was an ABI issue between aarch64 and x86_64. This issue can be solved easily with setting up some specific compilation flag.
